import Head from 'next/head';
import { useStyles } from '../styles/index.style';
import Movies from './Movies';

export default function Home() {
  const classes = useStyles();
  return (
    <>
      <Head>
        <title>The Movie Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.main}>
        <Movies />
      </main>
    </>
  );
}
